#!/usr/bin/env bash
# deploy-persona.sh
#
# Reads a persona's persona.json and generates the Hermes config.yaml for it,
# then optionally starts the persona's Hermes process.
#
# Usage:
#   ./scripts/deploy-persona.sh <path-to-persona-directory>
#
# Example:
#   ./scripts/deploy-persona.sh ../Council/personas/nora
#
# What this script does:
#   1. Validates persona.json exists and is well-formed
#   2. Creates the HERMES_HOME directory for the persona
#   3. Generates config.yaml from persona.json fields
#   4. Copies SOUL.md and AGENTS.md into HERMES_HOME
#   5. Copies skill files into HERMES_HOME/skills/
#   6. Creates a per-persona PostgreSQL schema
#   7. Prints the command to start the persona's Hermes process
#
# Requirements:
#   - jq (JSON parsing):   apt install jq
#   - psql (PostgreSQL):   apt install postgresql-client

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Arguments and validation
# ─────────────────────────────────────────────────────────────────────────────

PERSONA_DIR="${1:-}"

if [[ -z "$PERSONA_DIR" ]]; then
    echo "ERROR: No persona directory specified."
    echo "Usage: $0 <path-to-persona-directory>"
    exit 1
fi

if [[ ! -d "$PERSONA_DIR" ]]; then
    echo "ERROR: Directory not found: $PERSONA_DIR"
    exit 1
fi

PERSONA_JSON="$PERSONA_DIR/persona.json"

if [[ ! -f "$PERSONA_JSON" ]]; then
    echo "ERROR: persona.json not found in $PERSONA_DIR"
    exit 1
fi

# Validate JSON is parseable
if ! jq empty "$PERSONA_JSON" 2>/dev/null; then
    echo "ERROR: persona.json is not valid JSON"
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Read persona.json fields
# ─────────────────────────────────────────────────────────────────────────────

PERSONA_ID=$(jq -r '.id' "$PERSONA_JSON")
PERSONA_NAME=$(jq -r '.name' "$PERSONA_JSON")
PERSONA_VERSION=$(jq -r '.version' "$PERSONA_JSON")
HERMES_HOME=$(jq -r '.deployment.hermes_home' "$PERSONA_JSON")
PORT=$(jq -r '.deployment.port' "$PERSONA_JSON")

# Model provider
PROVIDER_TYPE=$(jq -r '.model_provider.primary.type' "$PERSONA_JSON")
PROVIDER_MODEL=$(jq -r '.model_provider.primary.model' "$PERSONA_JSON")
ROUTING=$(jq -r '.model_provider.routing' "$PERSONA_JSON")

# Local provider (used if routing = "local")
LOCAL_BASE_URL=$(jq -r '.model_provider.local.base_url // empty' "$PERSONA_JSON")
LOCAL_MODEL=$(jq -r '.model_provider.local.model // empty' "$PERSONA_JSON")

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Deploying persona: $PERSONA_NAME ($PERSONA_ID) v$PERSONA_VERSION"
echo "  HERMES_HOME: $HERMES_HOME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Create HERMES_HOME directory structure
# ─────────────────────────────────────────────────────────────────────────────

echo "[1/6] Creating HERMES_HOME at $HERMES_HOME"
mkdir -p "$HERMES_HOME/skills"

# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Generate config.yaml for Hermes
# ─────────────────────────────────────────────────────────────────────────────

echo "[2/6] Generating config.yaml"

# Determine provider string for Hermes
# Hermes uses "anthropic/model-name", "openai/model-name", or a base_url for local
if [[ "$ROUTING" == "local" && -n "$LOCAL_BASE_URL" ]]; then
    HERMES_MODEL="$LOCAL_MODEL"
    HERMES_BASE_URL="$LOCAL_BASE_URL"
elif [[ "$PROVIDER_TYPE" == "anthropic" ]]; then
    HERMES_MODEL="anthropic/$PROVIDER_MODEL"
    HERMES_BASE_URL=""
elif [[ "$PROVIDER_TYPE" == "openai" ]]; then
    HERMES_MODEL="openai/$PROVIDER_MODEL"
    HERMES_BASE_URL=""
else
    HERMES_MODEL="$PROVIDER_MODEL"
    HERMES_BASE_URL="$LOCAL_BASE_URL"
fi

cat > "$HERMES_HOME/config.yaml" <<EOF
# Hermes config for persona: $PERSONA_NAME
# Generated by deploy-persona.sh — do not edit manually.
# To change model or routing, edit persona.json and re-run deploy-persona.sh.

model: $HERMES_MODEL
${HERMES_BASE_URL:+base_url: $HERMES_BASE_URL}

display:
  skin: default

memory:
  enabled: true

# Persona identity files are loaded from this HERMES_HOME automatically:
#   SOUL.md    → agent identity (slot 1 in system prompt)
#   AGENTS.md  → domain rules and operating procedures
EOF

echo "    → config.yaml written"

# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Copy SOUL.md and AGENTS.md into HERMES_HOME
# ─────────────────────────────────────────────────────────────────────────────

echo "[3/6] Copying identity files"

if [[ ! -f "$PERSONA_DIR/SOUL.md" ]]; then
    echo "    ERROR: SOUL.md not found in $PERSONA_DIR"
    exit 1
fi

if [[ ! -f "$PERSONA_DIR/AGENTS.md" ]]; then
    echo "    ERROR: AGENTS.md not found in $PERSONA_DIR"
    exit 1
fi

cp "$PERSONA_DIR/SOUL.md"  "$HERMES_HOME/SOUL.md"
cp "$PERSONA_DIR/AGENTS.md" "$HERMES_HOME/AGENTS.md"
echo "    → SOUL.md copied"
echo "    → AGENTS.md copied"

# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — Copy skill files into HERMES_HOME/skills/
# ─────────────────────────────────────────────────────────────────────────────

echo "[4/6] Copying skill files"

SKILLS_DIR="$PERSONA_DIR/skills"
if [[ -d "$SKILLS_DIR" ]]; then
    SKILL_COUNT=$(find "$SKILLS_DIR" -name "*.SKILL.md" | wc -l)
    if [[ "$SKILL_COUNT" -gt 0 ]]; then
        cp "$SKILLS_DIR"/*.SKILL.md "$HERMES_HOME/skills/" 2>/dev/null || true
        echo "    → $SKILL_COUNT skill file(s) copied"
    else
        echo "    → No skill files found (ok for new personas)"
    fi
else
    echo "    → No skills/ directory (ok for new personas)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 5 — Create per-persona PostgreSQL schema
# ─────────────────────────────────────────────────────────────────────────────

echo "[5/6] Creating PostgreSQL schema for persona: $PERSONA_ID"

# Load DB credentials from infrastructure/.env if it exists
INFRA_ENV="$(dirname "$0")/../infrastructure/.env"
if [[ -f "$INFRA_ENV" ]]; then
    # shellcheck disable=SC1090
    source "$INFRA_ENV"
fi

PGUSER="${POSTGRES_USER:-}"
PGPASSWORD="${POSTGRES_PASSWORD:-}"
PGHOST="${POSTGRES_HOST:-localhost}"
PGPORT="${POSTGRES_PORT:-5432}"
PGDB="${POSTGRES_DB:-persona}"

if command -v psql &>/dev/null; then
    PGPASSWORD="$PGPASSWORD" psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDB" <<SQL
-- Create persona-scoped schema
CREATE SCHEMA IF NOT EXISTS ${PERSONA_ID};

-- Persona-specific DB user (read/write own schema only)
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'persona_${PERSONA_ID}') THEN
        CREATE ROLE persona_${PERSONA_ID} LOGIN PASSWORD '${PERSONA_ID}_changeme';
    END IF;
END
\$\$;

GRANT USAGE ON SCHEMA ${PERSONA_ID} TO persona_${PERSONA_ID};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${PERSONA_ID} TO persona_${PERSONA_ID};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${PERSONA_ID}
    GRANT ALL PRIVILEGES ON TABLES TO persona_${PERSONA_ID};

-- Allow persona to write to shared tables
GRANT INSERT ON audit_log TO persona_${PERSONA_ID};
GRANT INSERT, SELECT ON persona_health TO persona_${PERSONA_ID};
GRANT ALL PRIVILEGES ON persona_memory TO persona_${PERSONA_ID};
GRANT ALL PRIVILEGES ON goals TO persona_${PERSONA_ID};
SQL
    echo "    → Schema '$PERSONA_ID' created"
else
    echo "    WARNING: psql not found — skipping database setup."
    echo "    Run infrastructure/db/init.sql manually before starting the persona."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 6 — Print start command
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo "[6/6] Done. Start this persona with:"
echo ""
echo "  HERMES_HOME=$HERMES_HOME hermes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  $PERSONA_NAME deployed successfully."
echo "  Port: $PORT (for future gateway routing)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
